---
 - hosts: mywebservers
   become: yes
   tasks:
   - name: install tree
     apt: 
      name: tree
      state: present

   - name: install git
     apt:
      name: git
      state: present  

   - name: install apache
     apt:
      name: apache2 
      state: present 

   - name: i want to start apache2
     service:
      name: apache2
      state: restarted 

   - name: install webserver on redhat node side
     yum:
      name: httpd
      state: present
     when : ansible_os_family =="redhat"          
